// <auto-generated />
using System;
using Joonasw.ManagedIdentityFileSharingDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Joonasw.ManagedIdentityFileSharingDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190901150912_RemoveDescription")]
    partial class RemoveDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Joonasw.ManagedIdentityFileSharingDemo.Data.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("CreatorObjectId")
                        .HasMaxLength(64);

                    b.Property<string>("CreatorTenantId")
                        .HasMaxLength(64);

                    b.Property<string>("FileName")
                        .HasMaxLength(256);

                    b.Property<Guid>("StoredBlobId");

                    b.HasKey("Id");

                    b.ToTable("StoredFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
